# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[battery]
[[battery.display]]
threshold = 10
style = "bold red"

[cmd_duration]
disabled = true

[directory]
truncation_length = 3
truncate_to_repo = true
read_only = ""
truncation_symbol = "…/"
